### ISSUE TITLE
The code to generate expressions skeletons does not work.

### ISSUE THREAD

**Issue by ShimaKen-max** [AILWQ/Joint_Supervised_Learning_for_SR#1]
I followed the procedure you provided and executed the following command, but the progress bar did not advance from 0% for many hours.
# command
python data_creation/dataset_creation.py --number_of_expressions 200 --no-debug

![Screenshot from 2024-07-19 19-28-01](https://github.com/user-attachments/assets/a6e58bbf-afe3-4f94-b798-4dfe32210760)

How can I start the skeleton generation process?

**Comment by AILWQ** [comment]
> I followed the procedure you provided and executed the following command, but the progress bar did not advance from 0% for many hours.
> 
> # command
> python data_creation/dataset_creation.py --number_of_expressions 200 --no-debug
> 
> ![Screenshot from 2024-07-19 19-28-01](https://private-user-images.githubusercontent.com/167850861/350359451-a6e58bbf-afe3-4f94-b798-4dfe32210760.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2Njc0NTAsIm5iZiI6MTcyMjY2NzE1MCwicGF0aCI6Ii8xNjc4NTA4NjEvMzUwMzU5NDUxLWE2ZTU4YmJmLWFmZTMtNGY5NC1iNzk4LTRkZmUzMjIxMDc2MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwM1QwNjM5MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MjQwNmJhZWQyNzE0ZWE2ZTgyZDFhNjUyNWIwMTk1YjhmMmY1OWRlMmIwYTA1YWU4NzE5ODI4NjlkNTM0NjdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rUpmJ7SsJN5vfvkQR1-cQzcf2Ghwe350fhsMld0tz6k)
> 
> How can I start the skeleton generation process?

I have encountered this problem, but I have not found an exact solution. I suggest you try to run a few times, and the problem may be solved.
